Fixed typo
andresokol/andresokol.github.io pull request #1
Opened 2022-07-27 14:32 UTC by Whynot63

2022-07-27 14:35 UTC, andresokol reviewed
cc @topshik

2022-07-27 14:41 UTC, andresokol requested changes
Please change pull request description according to the contribution guideline - add the rationale and short description of proposed changes

2022-09-30 11:52 UTC, topshik commented
I think we need to rethink the architecture of the added feature. Let's have a call about it on Monday.

2022-09-30 11:53 UTC, topshik requested changes
Waiting for updates from your side.

2022-09-30 11:53 UTC, topshik commented on andresokol.work/index.html
> +                <p>гей миллиардер плейбой филантроп</p>
Let's try to use modern tools for the problem.

2022-11-09 08:47 UTC, andresokol commented
Closing due to inactivity

2022-11-09 08:47 UTC, closed without merging